import json
import os

new_code_source = [
    "import numpy as np\n",
    "\n",
    "def print_latex(M, precision=4):\n",
    "    import numpy as np\n",
    "    if not isinstance(M, np.ndarray):\n",
    "        latex_str = f\"{M}\"\n",
    "    elif M.ndim == 1:\n",
    "        inner = \" & \".join([f\"{x:.{precision}f}\" for x in M])\n",
    "        latex_str = f\"\\\\begin{{bmatrix}} {inner} \\\\end{{bmatrix}}\"\n",
    "    else:\n",
    "        rows = \" \\\\\\\\ \".join([\" & \".join([f\"{x:.{precision}f}\" for x in row]) for row in M])\n",
    "        latex_str = f\"\\\\begin{{bmatrix}} {rows} \\\\end{{bmatrix}}\"\n",
    "\n",
    "    try:\n",
    "        get_ipython()\n",
    "        in_jupyter = True\n",
    "    except NameError:\n",
    "        in_jupyter = False\n",
    "\n",
    "    if in_jupyter:\n",
    "        from IPython.display import display, Math\n",
    "        display(Math(latex_str))\n",
    "    else:\n",
    "        print(f\"$$ {latex_str} $$\")\n",
    "\n",
    "def Vien_Quanh(A):\n",
    "    SEP = \"═\" * 62\n",
    "    sep = \"─\" * 62\n",
    "    print(SEP)\n",
    "    print(\"    TÌM MA TRẬN NGHỊCH ĐẢO BẰNG PHƯƠNG PHÁP VIỀN QUANH\")\n",
    "    print(SEP)\n",
    "\n",
    "    n = len(A)\n",
    "    print(\"\\nI. CƠ SỞ LÝ THUYẾT\")\n",
    "    print(\"   Tính ma trận nghịch đảo A_k⁻¹ của các ma trận con chính A_k (k=1..n).\")\n",
    "    print(\"   Tại bước k, phân hoạch A_k = [A_{k-1}  u_k ; v_k^T  a_kk].\")\n",
    "    print(\"   Tính x_k = A_{k-1}⁻¹·u_k,  y_k^T = v_k^T·A_{k-1}⁻¹.\")\n",
    "    print(\"   Tính α_k = a_kk - v_k^T·x_k. Nếu α_k = 0, A suy biến.\")\n",
    "    print(\"   Tính các khối của A_k⁻¹:\")\n",
    "    print(\"     s_k = 1/α_k, q_k = -s_k·x_k, r_k^T = -s_k·y_k^T\")\n",
    "    print(\"     P_k = A_{k-1}⁻¹ + s_k·x_k·y_k^T\")\n",
    "    print(\"     A_k⁻¹ = [P_k  q_k ; r_k^T  s_k]\")\n",
    "\n",
    "    print(f\"\\nII. DỮ LIỆU BÀI TOÁN\")\n",
    "    print(f\"   Ma trận A ({n}×{n}):\")\n",
    "    print_latex(A, precision=4)\n",
    "\n",
    "    print(f\"\\nIII. QUÁ TRÌNH TÍNH TOÁN\")\n",
    "    if abs(A[0, 0]) < 1e-14:\n",
    "        print(\"   => LỖI: a_11 = 0. Phương pháp viền quanh cơ bản thất bại.\")\n",
    "        return\n",
    "\n",
    "    A_inv_k = np.array([[1.0 / A[0, 0]]])\n",
    "    print(f\"\\n   -- Bước 1 (k = 1) --\")\n",
    "    print(f\"   A_1 = [{A[0,0]:.4f}], A_1⁻¹ = [{A_inv_k[0,0]:.6f}]\")\n",
    "\n",
    "    for k in range(2, n + 1):\n",
    "        print(f\"\\n   -- Bước {k} (k = {k}) --\")\n",
    "        # u_k is column k-1 of A from row 0 to k-2\n",
    "        u_k = A[0:k-1, k-1].reshape(-1, 1)\n",
    "        # v_k_T is row k-1 of A from col 0 to k-2\n",
    "        v_k_T = A[k-1, 0:k-1].reshape(1, -1)\n",
    "        a_kk = A[k-1, k-1]\n",
    "\n",
    "        print(f\"   u_k:\")\n",
    "        print_latex(u_k, precision=4)\n",
    "        print(f\"   v_k^T:\")\n",
    "        print_latex(v_k_T, precision=4)\n",
    "\n",
    "        x_k = A_inv_k @ u_k\n",
    "        y_k_T = v_k_T @ A_inv_k\n",
    "\n",
    "        alpha_k = a_kk - (v_k_T @ x_k)[0, 0]\n",
    "        print(f\"   α_k = a_kk - v_k^T·x_k = {a_kk:.4f} - {(a_kk - alpha_k):.4f} = {alpha_k:.6f}\")\n",
    "\n",
    "        if abs(alpha_k) < 1e-14:\n",
    "            print(f\"   => LỖI: α_{k} = 0. Ma trận con A_{k} suy biến. Dừng thuật toán.\")\n",
    "            return\n",
    "\n",
    "        s_k = 1.0 / alpha_k\n",
    "        q_k = -s_k * x_k\n",
    "        r_k_T = -s_k * y_k_T\n",
    "        P_k = A_inv_k + s_k * (x_k @ y_k_T)\n",
    "\n",
    "        A_inv_next = np.zeros((k, k))\n",
    "        A_inv_next[0:k-1, 0:k-1] = P_k\n",
    "        A_inv_next[0:k-1, k-1] = q_k.flatten()\n",
    "        A_inv_next[k-1, 0:k-1] = r_k_T.flatten()\n",
    "        A_inv_next[k-1, k-1] = s_k\n",
    "\n",
    "        A_inv_k = A_inv_next\n",
    "        print(f\"   Ma trận A_{k}⁻¹:\")\n",
    "        print_latex(A_inv_k, precision=6)\n",
    "\n",
    "    print(f\"\\nIV. KẾT LUẬN\")\n",
    "    print(\"   Ma trận nghịch đảo A⁻¹:\")\n",
    "    print_latex(A_inv_k, precision=6)\n",
    "    err = np.linalg.norm(A @ A_inv_k - np.eye(n), np.inf)\n",
    "    print(f\"   Kiểm tra: ||A·A⁻¹ − I||∞ = {err:.2e}  {'✓' if err < 1e-6 else '≈0'}\")\n",
    "\n",
    "\n",
    "# Ví dụ ma trận A\n",
    "A = np.array([\n",
    "    [1.0, 2.0, 3.0],\n",
    "    [2.0, 3.0, 4.0],\n",
    "    [3.0, 4.0, 6.0]\n",
    "])\n",
    "\n",
    "Vien_Quanh(A)\n"
]

def update_notebook(path):
    with open(path, 'r', encoding='utf-8') as f:
        nb = json.load(f)
    for cell in nb['cells']:
        if cell['cell_type'] == 'code':
            src = "".join(cell.get('source', []))
            if 'def print_latex' in src and 'def Vien_Quanh' in src:
                cell['source'] = new_code_source
    with open(path, 'w', encoding='utf-8') as f:
        json.dump(nb, f, indent=1, ensure_ascii=False)

nb1 = r'd:\code\Uni\On_thi_cuoi_ky\Giải tích số\scripts\Giai_tich_so.ipynb'
nb2 = r'd:\code\Uni\On_thi_cuoi_ky\Giải tích số\scripts\CHƯƠNG 4 GIẢI HỆ ĐẠI SỐ TUYẾN TÍNH & TÌM MA TRẬN NGHỊCH ĐẢO\Viền quanh.ipynb'

update_notebook(nb1)
update_notebook(nb2)
